name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: check repository
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Clean old redis
        run: |
          python -m pip uninstall -y redis

      - name: install dependencies
        run: | 
          python -m venv .venv
          .venv/bin/python -m pip install --upgrade pip
          .venv/bin/python -m pip install -r requirements.txt

      - name: Check redis version
        run: |
         .venv/bin/python -c "import redis; print(redis.__file__, redis.__version__)"

      - name: run tests
        run: |
          export PYTHONPATH=.
          .venv/bin/python -m pytest --cov=src --cov-report=xml


